name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
      
    - name: git pull
      run: git pull origin master
    - name: git submodule update
      run: git submodule update
    - name: git submodule foreach git pull
      run: git submodule foreach git pull 
      
    - name: Delete useless lines (1)
      run: sed $'s/\r$//' ./gradlew > ./gradlew2
    - name: Delete useless lines (2)
      run: rm ./gradlew
    - name: Delete useless lines (3)
      run: mv ./gradlew2 ./gradlew
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle (1)
      run: gradle wrapper
    - name: Build with Gradle (2)
      run: ./gradlew build -x test
      
    - name: git add
      run: git add .
    - name: Configure git (1)
      run: git config --global user.email "github@github.com"
    - name: Configure git (2)
      run: git config --global user.name "Github Bot"
    - name: Git commit
      run: git commit -m "artifact" 
      
    - name: git pull (1)
      run: git config pull.rebase false
    - name: git pull (2)
      run: git pull origin master
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
